[platformio]
default_envs =
	adafruit_feather_esp32_v2
	adafruit_feather_esp32s3
	adafruit_feather_esp32s3_reversetft

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

;debug_tool = esp-prog
;upload_protocol = esp-prog
upload_protocol = esptool

extra_scripts = pre:scons_pre.py

[common]

build_unflags_std = 
	-std=gnu++11
	-std=gnu++14

build_flags_std = 
	-std=gnu++17

build_flags_env =
	-DMONITOR_SPEED=${env.monitor_speed}
	-DFASTLED_ALL_PINS_HARDWARE_SPI

build_flags_v2 = 
	; v2 VSPI pins are GPIO 18, 19, 23, & 5
	; (HSPI are GPIO 14, 12, 13, & 15 which we reserve for JTAG)
	-DFASTLED_ESP32_SPI_BUS=VSPI

build_flags_s3 = 
	; builtin USB on ESP32S3 requires this for upload/monitor to work as expected
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	; S3 allows fastled SPI on any pins
	-DFASTLED_ESP32_SPI_BUS=FSPI

lib_deps_etl = 
	etlcpp/Embedded Template Library@^20.38.2

lib_deps_fastled = 
	fastled/FastLED@^3.6.0

lib_deps_motion = 
	adafruit/Adafruit Sensor Calibration@^1.1.5
	adafruit/Adafruit LIS3MDL@^1.2.1
	adafruit/Adafruit LSM6DS@^4.7.0

lib_deps_tft = 
	adafruit/Adafruit GFX Library@^1.11.9
	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3

[env:adafruit_feather_esp32_v2]
board = adafruit_feather_esp32_v2
build_unflags =
	${common.build_unflags_std}
build_flags =
	${common.build_flags_std}
	${common.build_flags_env}
	${common.build_flags_v2}
lib_deps = 
	${common.lib_deps_etl}
	${common.lib_deps_fastled}
	${common.lib_deps_motion}

[env:adafruit_feather_esp32s3]
board = adafruit_feather_esp32s3
build_unflags =
	${common.build_unflags_std}
build_flags =
	${common.build_flags_std}
	${common.build_flags_env}
	${common.build_flags_s3}
lib_deps = 
	${common.lib_deps_etl}
	${common.lib_deps_fastled}
	${common.lib_deps_motion}

[env:adafruit_feather_esp32s3_reversetft]
board = adafruit_feather_esp32s3_reversetft
build_unflags =
	${common.build_unflags_std}
build_flags =
	${common.build_flags_std}
	${common.build_flags_env}
	${common.build_flags_s3}
lib_deps = 
	${common.lib_deps_etl}
	${common.lib_deps_fastled}
	${common.lib_deps_motion}
	${common.lib_deps_tft}
